# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '2'

services:
  db:
    image: mariadb
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: pantheon
      MYSQL_USER: pantheon
      MYSQL_PASSWORD: pantheon
    volumes:
      - ./artifacts:/docker-entrypoint-initdb.d
    networks:
      - code-network
      - db-network

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    restart: always
    networks:
      - mail-network

  web:
    image: nginx:latest
    environment:
      WEBROOT: /var/www/html/web
    ports:
      - 80:80
    volumes:
      - tmp:/tmp
      - ./certs:/certs
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
      - cache-network

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
    volumes:
      - tmp:/tmp
      - .:/var/www/html
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network
      - cache-network
      - db-network
      - mail-network

networks:
  code-network:
    driver: bridge
  db-network:
    driver: bridge
  cache-network:
    driver: bridge
  mail-network:
    driver: bridge

volumes:
  db:
  tmp: